---
# Copyright (C) 2016 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: LGPL-3.0-or-later

- name: Restart gdnsd
  ansible.builtin.service:
    name: 'gdnsd'
    state: restarted
